// PostgreSQL 18.4 catalog MCP server — generated by mcpify. Do not hand-edit.
//
// Regression test for Fix 8b (embedding population completeness): asserts
// that every version's `semantic_endpoints` row count EQUALS its
// `endpoints` row count — not just "greater than zero". A store can end
// up with `endpoints` rows but only some (or none) of the matching
// `semantic_endpoints` rows if `bin/populate_embeddings.rs` was run with
// a stale binary, was interrupted mid-run, or (before Fix 8a) defaulted
// to only the default version's store. `search` silently returns
// incomplete/empty results for an under-populated version with no error
// ever surfaced, so this must be caught here rather than discovered live.
//
// This publication-oriented project commits populated, curated stores, so
// parity and the reviewed per-version operation counts are ordinary CI
// invariants rather than an ignored post-generation check.

use postgres_mcp::data::store::{VERSION_STORE_FILES, open_store, resolve_store_path};

#[test]
fn semantic_endpoints_row_count_matches_endpoints_row_count_for_every_version() {
    let mut mismatches = Vec::new();

    for (label, _file) in VERSION_STORE_FILES {
        let path = resolve_store_path(label)
            .unwrap_or_else(|err| panic!("failed to resolve store path for '{label}': {err}"));
        let conn = open_store(&path)
            .unwrap_or_else(|err| panic!("failed to open store for '{label}': {err}"));

        let endpoints_count: i64 = conn
            .query_row("SELECT count(*) FROM endpoints", [], |row| row.get(0))
            .unwrap_or_else(|err| panic!("failed to count 'endpoints' rows for '{label}': {err}"));
        let semantic_count: i64 = conn
            .query_row("SELECT count(*) FROM semantic_endpoints", [], |row| {
                row.get(0)
            })
            .unwrap_or_else(|err| {
                panic!("failed to count 'semantic_endpoints' rows for '{label}': {err}")
            });

        let expected_count = match *label {
            "18" => 500,
            "17" => 476,
            "16" => 460,
            "15" => 451,
            "14" => 439,
            "19beta2" => 492,
            other => panic!("missing curated operation count for version '{other}'"),
        };

        if endpoints_count != semantic_count || endpoints_count != expected_count {
            mismatches.push(format!(
                "'{label}': endpoints={endpoints_count} semantic_endpoints={semantic_count} expected={expected_count}"
            ));
        }
    }

    assert!(
        mismatches.is_empty(),
        "embedding population incomplete — semantic_endpoints row count must equal endpoints \
         row count for every version, but found mismatch(es): {}",
        mismatches.join("; ")
    );
}

#[test]
fn stores_contain_only_postgresql_catalog_fields_and_humanized_prose() {
    for (label, _file) in VERSION_STORE_FILES {
        let path = resolve_store_path(label).unwrap();
        let conn = open_store(&path).unwrap();
        let legacy_auth_columns: i64 = conn
            .query_row(
                "SELECT count(*) FROM pragma_table_info('endpoints') \
                 WHERE name = 'auth_scheme_ref'",
                [],
                |row| row.get(0),
            )
            .unwrap();
        let prose_with_underscores: i64 = conn
            .query_row(
                r"SELECT count(*) FROM endpoints
                  WHERE coalesce(summary, '') LIKE '%\_%' ESCAPE '\'
                     OR coalesce(description, '') LIKE '%\_%' ESCAPE '\'",
                [],
                |row| row.get(0),
            )
            .unwrap();

        assert_eq!(legacy_auth_columns, 0, "version {label}");
        assert_eq!(prose_with_underscores, 0, "version {label}");
    }
}
