// PostgreSQL 18.4 catalog MCP server — generated by mcpify. Do not hand-edit.

use postgres_mcp::auth::auth_manager::AuthManager;
use postgres_mcp::core::config_manager::load_config;
use postgres_mcp::core::config_schema::Transport;
use postgres_mcp::core::errors::McpifyError;
use postgres_mcp::data::store::{cached_store_connection, get_endpoint};
use postgres_mcp::tools::call_tool::call_operation;

pub async fn run(operation_id: &str, args_json: &str) -> anyhow::Result<()> {
    let config = load_config(serde_json::Map::new())?;
    let mut auth_manager = AuthManager::new(config.auth_method);
    let args: serde_json::Value = serde_json::from_str(args_json)?;

    let endpoint = {
        let conn = cached_store_connection(&config.api_version)?
            .lock()
            .unwrap();
        get_endpoint(&conn, operation_id)?
            .ok_or_else(|| McpifyError::NotFound(format!("unknown operationId '{operation_id}'")))?
    };

    let credentials = auth_manager
        .postgres_credentials(Transport::Stdio, None)
        .await?;

    let result = call_operation(&endpoint, &config, &credentials, operation_id, args).await?;
    println!("{}", serde_json::to_string_pretty(&result)?);
    Ok(())
}
