// PostgreSQL 18.4 catalog MCP server — generated by mcpify. Do not hand-edit.
//
// Interactive setup wizard (REQ-1.6): collects the PostgreSQL connection URL
// and credentials, then persists them per
// the operator's choice: a .env file, a local or global config.yml file,
// or a ready-to-run environment invocation printed to stdout (nothing written to
// disk).
// `inquire`'s prompts are blocking — run through `spawn_blocking`, the
// same pattern mcpify's own `auth_profile::prompt` documents for calling
// it from an async runtime.

use std::collections::HashMap;
use std::str::FromStr;

use postgres_mcp::core::config_schema::{AuthMethod, Transport};
use postgres_mcp::core::credential_storage::save_credential;

fn to_env_key(key: &str) -> String {
    key.to_uppercase()
}

fn shell_quote(value: &str) -> String {
    format!("'{}'", value.replace('\'', "'\"'\"'"))
}

fn validate_postgres_url(url: &str) -> anyhow::Result<()> {
    let parsed = tokio_postgres::Config::from_str(url)
        .map_err(|error| anyhow::anyhow!("invalid PostgreSQL connection URL: {error}"))?;
    anyhow::ensure!(
        parsed.get_password().is_none(),
        "do not put a password in the PostgreSQL URL; enter it at the separate password prompt"
    );
    Ok(())
}

async fn prompt_base_url() -> anyhow::Result<String> {
    let url = tokio::task::spawn_blocking(|| {
        inquire::Text::new("PostgreSQL connection URL (postgresql://host/database):").prompt()
    })
    .await??;
    validate_postgres_url(&url)?;
    Ok(url)
}

async fn prompt_auth_method() -> anyhow::Result<AuthMethod> {
    // PostgreSQL negotiates the server-side password exchange (for example
    // SCRAM-SHA-256 or MD5) from pg_hba.conf; the client supplies a username
    // and password in either case.
    Ok(AuthMethod::Password)
}

// mcpify:versions:begin
async fn prompt_api_version() -> anyhow::Result<String> {
    let choices = vec!["18 (default/latest)", "17", "16", "15", "14", "19beta2"];
    let selection = tokio::task::spawn_blocking(move || {
        inquire::Select::new("API version to use:", choices).prompt()
    })
    .await??;

    Ok(match selection {
        "18 (default/latest)" => "18".to_string(),
        "17" => "17".to_string(),
        "16" => "16".to_string(),
        "15" => "15".to_string(),
        "14" => "14".to_string(),
        "19beta2" => "19beta2".to_string(),
        other => other.to_string(),
    })
}
// mcpify:versions:end

async fn prompt_transport() -> anyhow::Result<Transport> {
    let choices = vec![
        "stdio (spawned as a subprocess by the MCP client)",
        "http (a standalone server the MCP client connects to over the network)",
    ];
    let selection = tokio::task::spawn_blocking(move || {
        inquire::Select::new("Which transport will this deployment use?", choices).prompt()
    })
    .await??;

    Ok(if selection.starts_with("stdio") {
        Transport::Stdio
    } else {
        Transport::Http
    })
}

async fn prompt_credentials(auth_method: AuthMethod) -> anyhow::Result<HashMap<String, String>> {
    match auth_method {
        AuthMethod::Password => {
            tokio::task::spawn_blocking(move || -> anyhow::Result<HashMap<String, String>> {
                let mut credentials = HashMap::new();
                credentials.insert(
                    "username".to_string(),
                    inquire::Text::new("Username:").prompt()?,
                );
                credentials.insert(
                    "password".to_string(),
                    inquire::Password::new("Password:")
                        .without_confirmation()
                        .prompt()?,
                );
                Ok(credentials)
            })
            .await?
        }
    }
}

/// Persists the non-secret config fields (`url`/`auth_method`/`api_version`/
/// `transport`) as YAML matching exactly what `config_manager::load_config`
/// reads back — never the credential fields, which stay in the OS
/// keychain/encrypted-file fallback via `save_credential` (called by the
/// caller before this runs). Writing anywhere else (a stray `.env`-only
/// var name, `config.json`, etc.) would leave the persisted config silently
/// ignored on every subsequent run, since `load_config`'s cascade only ever
/// reads `./postgresql-mcp.config.yml` (local) or
/// `~/.postgresql-mcp/config.yml` (global).
async fn write_config_yaml(
    path: &std::path::Path,
    config_fields: &serde_json::Value,
) -> anyhow::Result<()> {
    let yaml = serde_yaml::to_string(config_fields)?;
    if let Some(parent) = path.parent()
        && !parent.as_os_str().is_empty()
    {
        std::fs::create_dir_all(parent)?;
    }
    std::fs::write(path, yaml)?;
    println!("Wrote {}", path.display());
    println!(
        "Credentials are never written to this file — they're stored via the OS \
         keychain/encrypted-file fallback from the credential prompt above."
    );
    Ok(())
}

async fn prompt_persistence(
    env: &HashMap<String, String>,
    config_fields: &serde_json::Value,
) -> anyhow::Result<()> {
    let choices = vec![
        "Write a .env file",
        "Write a config.yml file (global — ~/.postgresql-mcp/config.yml, read on every invocation on this machine)",
        "Write a config.yml file (local — ./postgresql-mcp.config.yml, read only from this directory)",
        "Print a ready-to-run environment invocation (nothing written to disk)",
    ];
    let selection = tokio::task::spawn_blocking(move || {
        inquire::Select::new("How should these settings be saved?", choices).prompt()
    })
    .await??;

    persist_selection(selection, env, config_fields).await
}

async fn persist_selection(
    selection: &str,
    env: &HashMap<String, String>,
    config_fields: &serde_json::Value,
) -> anyhow::Result<()> {
    let local_dir = std::env::current_dir()?;
    let global_config =
        postgres_mcp::core::credential_storage::resolve_home_dir().join(".postgresql-mcp/config.yml");
    persist_selection_at(selection, env, config_fields, &local_dir, &global_config).await
}

async fn persist_selection_at(
    selection: &str,
    env: &HashMap<String, String>,
    config_fields: &serde_json::Value,
    local_dir: &std::path::Path,
    global_config: &std::path::Path,
) -> anyhow::Result<()> {
    match selection {
        "Write a .env file" => {
            let contents = env
                .iter()
                .map(|(key, value)| format!("{key}={value}"))
                .collect::<Vec<_>>()
                .join("\n");
            let path = local_dir.join(".env");
            std::fs::write(&path, format!("{contents}\n"))?;
            #[cfg(unix)]
            {
                use std::os::unix::fs::PermissionsExt;
                std::fs::set_permissions(&path, std::fs::Permissions::from_mode(0o600))?;
            }
            println!("Wrote .env");
        }
        s if s.starts_with("Write a config.yml file (global") => {
            write_config_yaml(global_config, config_fields).await?;
        }
        s if s.starts_with("Write a config.yml file (local") => {
            write_config_yaml(&local_dir.join("postgresql-mcp.config.yml"), config_fields).await?;
        }
        _ => {
            let assignments = env
                .iter()
                .map(|(key, value)| format!("{key}={}", shell_quote(value)))
                .collect::<Vec<_>>()
                .join(" ");
            println!("{assignments} postgresql-mcp start");
        }
    }
    Ok(())
}

fn build_runtime_settings(
    url: String,
    auth_method: AuthMethod,
    api_version: String,
    transport: Transport,
    credentials: &HashMap<String, String>,
) -> anyhow::Result<(HashMap<String, String>, serde_json::Value)> {
    let mut env = HashMap::new();
    env.insert("POSTGRES_MCP_DATABASE_URL".to_string(), url);
    env.insert(
        "POSTGRES_MCP_AUTH_METHOD".to_string(),
        serde_json::to_value(auth_method)?
            .as_str()
            .unwrap_or_default()
            .to_string(),
    );
    env.insert("POSTGRES_MCP_API_VERSION".to_string(), api_version);
    env.insert(
        "POSTGRES_MCP_TRANSPORT".to_string(),
        serde_json::to_value(transport)?
            .as_str()
            .unwrap_or_default()
            .to_string(),
    );
    for (key, value) in credentials {
        env.insert(format!("POSTGRES_MCP_{}", to_env_key(key)), value.clone());
    }

    let config_fields = serde_json::json!({
        "url": env.get("POSTGRES_MCP_DATABASE_URL"),
        "auth_method": env.get("POSTGRES_MCP_AUTH_METHOD"),
        "api_version": env.get("POSTGRES_MCP_API_VERSION"),
        "transport": env.get("POSTGRES_MCP_TRANSPORT"),
    });
    Ok((env, config_fields))
}

/// Prints a ready-to-use MCP client config (the `mcpServers` block a host
/// like Claude Code/Desktop expects) for whichever transport was selected
/// — the stdio and http shapes are mutually exclusive, never both, since
/// they're two different ways of running this same server and a client
/// only ever picks one. HTTP transport shows credentials as headers only
/// (never env/CLI args, matching `AuthManager::postgres_credentials`'s
/// HTTP-only-uses-per-request-credentials behavior); stdio places the
/// connection and credentials in the spawned process's `env` block.
fn print_mcp_client_config(transport: Transport, env: &HashMap<String, String>) {
    match transport {
        Transport::Stdio => {
            let config = serde_json::json!({
                "mcpServers": {
                    "postgresql-mcp": {
                        "command": "postgresql-mcp",
                        "args": ["start"],
                        "env": env,
                    }
                }
            });
            println!("\nMCP client config (stdio):");
            println!("{}", serde_json::to_string_pretty(&config).unwrap());
        }
        Transport::Http => {
            let header_name = "Authorization";
            let mut headers = serde_json::Map::new();
            headers.insert(
                header_name.to_string(),
                serde_json::Value::String("Basic <base64(username:password)>".to_string()),
            );
            let config = serde_json::json!({
                "mcpServers": {
                    "postgresql-mcp": {
                        "url": "http://127.0.0.1:3000/mcp",
                        "headers": headers,
                    }
                }
            });
            println!(
                "\nMCP client config (http) — adjust the host/port to match how you run \
                 `postgresql-mcp http`:"
            );
            println!("{}", serde_json::to_string_pretty(&config).unwrap());
            println!(
                "Credentials are never read from local config/env over HTTP transport — \
                 every request must carry its own \"{header_name}\" header."
            );
        }
    }
}

pub async fn run_setup_wizard() -> anyhow::Result<()> {
    let url = prompt_base_url().await?;
    let auth_method = prompt_auth_method().await?;
    let credentials = prompt_credentials(auth_method).await?;
    let api_version = prompt_api_version().await?;
    let transport = prompt_transport().await?;

    save_credential("active-credentials", &serde_json::to_string(&credentials)?)?;

    let (env, config_fields) =
        build_runtime_settings(url, auth_method, api_version, transport, &credentials)?;

    prompt_persistence(&env, &config_fields).await?;
    print_mcp_client_config(transport, &env);

    let run_command = match transport {
        Transport::Stdio => "start",
        Transport::Http => "http",
    };
    println!("Setup complete! Run: postgresql-mcp {run_command}");
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn setup_accepts_postgresql_urls_but_rejects_embedded_passwords() {
        assert!(validate_postgres_url("postgresql://db.example/app").is_ok());
        assert!(validate_postgres_url("postgresql://alice:secret@db.example/app").is_err());
        assert!(validate_postgres_url("https://db.example/app").is_err());
    }

    #[test]
    fn runtime_settings_keep_postgresql_config_and_credentials() {
        let credentials = HashMap::from([
            ("client_id".to_string(), "client".to_string()),
            ("authorization_code".to_string(), "spent-code".to_string()),
        ]);
        let (env, config) = build_runtime_settings(
            "postgresql://db.example/app".to_string(),
            AuthMethod::Password,
            "18".to_string(),
            Transport::Stdio,
            &credentials,
        )
        .unwrap();

        assert_eq!(config["url"], "postgresql://db.example/app");
        assert_eq!(config["transport"], "stdio");
        assert_eq!(env["POSTGRES_MCP_CLIENT_ID"], "client");
        assert_eq!(env["POSTGRES_MCP_AUTHORIZATION_CODE"], "spent-code");
    }

    #[tokio::test]
    async fn noninteractive_output_paths_cover_both_transports() {
        let credentials = HashMap::new();
        let (env, config) = build_runtime_settings(
            "postgresql://db.example/app".to_string(),
            // Not `prompt_auth_method().await.unwrap()`/`prompt_api_version().await.unwrap()`:
            // this test exercises the *non*-interactive output paths
            // (`persist_selection`/`print_mcp_client_config`), but those
            // prompt functions are only non-interactive themselves when
            // there's exactly one choice to make -- with more than one
            // auth method or API version they call `inquire::Select`,
            // which needs a real TTY and panics with "The input device is
            // not a TTY" in CI. Constructing the values directly (matching
            // what `print_mcp_client_config` below already hardcodes)
            // keeps this test TTY-independent regardless of how many
            // schemes/versions the spec declares.
            AuthMethod::Password,
            "18".to_string(),
            Transport::Http,
            &credentials,
        )
        .unwrap();
        persist_selection("Print a ready-to-run environment invocation", &env, &config)
            .await
            .unwrap();
        print_mcp_client_config(Transport::Stdio, &env);
        print_mcp_client_config(Transport::Http, &env);
    }

    #[tokio::test]
    async fn file_persistence_writes_env_local_yaml_and_global_yaml() {
        let dir = tempfile::tempdir().unwrap();
        let local_dir = dir.path().join("local");
        let global_config = dir.path().join("global/config.yml");
        std::fs::create_dir_all(&local_dir).unwrap();

        let credentials = HashMap::new();
        let (env, config) = build_runtime_settings(
            "postgresql://db.example/app".to_string(),
            AuthMethod::Password,
            "18".to_string(),
            Transport::Stdio,
            &credentials,
        )
        .unwrap();
        persist_selection_at(
            "Write a .env file",
            &env,
            &config,
            &local_dir,
            &global_config,
        )
        .await
        .unwrap();
        persist_selection_at(
            "Write a config.yml file (local — ./postgresql-mcp.config.yml, read only from this directory)",
            &env,
            &config,
            &local_dir,
            &global_config,
        )
        .await
        .unwrap();
        persist_selection_at(
            "Write a config.yml file (global — ~/.postgresql-mcp/config.yml, read on every invocation on this machine)",
            &env,
            &config,
            &local_dir,
            &global_config,
        )
        .await
        .unwrap();

        assert!(local_dir.join(".env").is_file());
        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            assert_eq!(
                std::fs::metadata(local_dir.join(".env"))
                    .unwrap()
                    .permissions()
                    .mode()
                    & 0o777,
                0o600
            );
        }
        assert!(local_dir.join("postgresql-mcp.config.yml").is_file());
        assert!(global_config.is_file());
    }
}
