// PostgreSQL 18.4 catalog MCP server — generated by mcpify. Do not hand-edit.

use axum::http::{HeaderMap, header};

use crate::auth::request_credentials::RequestCredentials;

#[derive(Debug, PartialEq)]
pub enum ExtractError {
    /// The PostgreSQL username/password envelope was absent or invalid.
    Missing,
}

/// Extracts PostgreSQL username/password credentials from the incoming
/// request's Basic Authorization header. HTTP is only the MCP transport;
/// the decoded credentials are used for a native PostgreSQL connection.
pub fn extract_request_credentials(
    headers: &HeaderMap,
) -> Result<RequestCredentials, ExtractError> {
    let value = headers
        .get(header::AUTHORIZATION)
        .and_then(|value| value.to_str().ok())
        .filter(|value| !value.is_empty())
        .ok_or(ExtractError::Missing)?;

    RequestCredentials::from_authorization_header(value).map_err(|_| ExtractError::Missing)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn extracts_a_present_header() {
        let mut headers = HeaderMap::new();
        headers.insert("Authorization", "Basic YWxpY2U6c2VjcmV0".parse().unwrap());
        let creds = extract_request_credentials(&headers).unwrap();
        assert_eq!(creds.username, "alice");
        assert_eq!(creds.password, "secret");
    }

    #[test]
    fn errors_when_the_header_is_absent() {
        let headers = HeaderMap::new();
        assert_eq!(
            extract_request_credentials(&headers),
            Err(ExtractError::Missing)
        );
    }

    #[test]
    fn errors_when_the_header_is_present_but_empty() {
        let mut headers = HeaderMap::new();
        headers.insert("Authorization", "".parse().unwrap());
        assert_eq!(
            extract_request_credentials(&headers),
            Err(ExtractError::Missing)
        );
    }

    #[test]
    fn rejects_non_basic_authorization() {
        let mut headers = HeaderMap::new();
        headers.insert("Authorization", "Bearer not-supported".parse().unwrap());
        assert_eq!(
            extract_request_credentials(&headers),
            Err(ExtractError::Missing)
        );
    }
}
