// PostgreSQL catalog MCP server — generated by mcpify. Do not hand-edit.

use tracing_subscriber::Registry;
use tracing_subscriber::fmt::writer::BoxMakeWriter;
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::{EnvFilter, Layer, fmt};

use super::log_transport::use_pretty_output;

const LOG_LEVEL_ENV_VAR: &str = "POSTGRES_MCP_LOG_LEVEL";
const TRANSPORT_ENV_VAR: &str = "POSTGRES_MCP_TRANSPORT";

/// A type-erased `tracing_subscriber` layer — lets `otel::build_layer`'s
/// OpenTelemetry bridge layer compose into the same subscriber
/// `init_logging` installs, without `init_logging` needing to name
/// `otel`'s concrete layer type.
pub type BoxedLayer = Box<dyn Layer<Registry> + Send + Sync>;

fn resolve_log_level_from(value: Option<String>) -> String {
    value.unwrap_or_else(|| "info".to_string())
}

/// `POSTGRES_MCP_LOG_LEVEL`, defaulting to `"info"` when unset.
pub fn resolve_log_level() -> String {
    resolve_log_level_from(std::env::var(LOG_LEVEL_ENV_VAR).ok())
}

/// `true` when the active transport is HTTP, in which case stdout carries
/// no protocol traffic and logs go there instead of stderr — see
/// `init_logging`.
pub fn logs_to_stdout() -> bool {
    std::env::var(TRANSPORT_ENV_VAR).as_deref() == Ok("http")
}

/// Installs the process-global structured logger: JSON output (pretty on an
/// interactive TTY), level from `resolve_log_level()`. Field-level secret
/// redaction isn't automatic here; call `sanitizer::sanitize` before logging
/// any user-controlled JSON payload.
///
/// `otel_layer` is composed into the same subscriber when tracing export is
/// enabled (see `otel::build_layer`), since `tracing` only allows a single
/// global default subscriber — the two layers can't be installed
/// independently without one call overwriting the other. Call once, at
/// process startup.
pub fn init_logging(otel_layer: Option<BoxedLayer>) {
    let filter = EnvFilter::try_new(resolve_log_level()).unwrap_or_else(|_| EnvFilter::new("info"));
    // The MCP stdio transport (see `mcp_server::connect_stdio`) speaks
    // JSON-RPC over stdout — any other writer sharing that stream
    // (tracing's default) corrupts every frame parsed on the client side.
    // Logs go to stderr in stdio mode, and to stdout in HTTP mode, where
    // stdout carries no protocol traffic and is the conventional log
    // destination.
    let writer: BoxMakeWriter = if logs_to_stdout() {
        BoxMakeWriter::new(std::io::stdout)
    } else {
        BoxMakeWriter::new(std::io::stderr)
    };
    let fmt_layer: BoxedLayer = if use_pretty_output() {
        fmt::layer().pretty().with_writer(writer).boxed()
    } else {
        fmt::layer().json().with_writer(writer).boxed()
    };

    // `fmt_layer`/`otel_layer` are boxed as `Layer<Registry>` specifically,
    // so they must land directly on the bare `registry()` (a single
    // `Vec<BoxedLayer>` `.with()` call, since `Vec<L>` itself implements
    // `Layer<S>`) before anything — including the filter — changes the
    // accumulated subscriber's type; `EnvFilter` implements `Layer<S>`
    // generically for any `S`, so it can compose on top afterward.
    let layers: Vec<BoxedLayer> = std::iter::once(fmt_layer).chain(otel_layer).collect();

    tracing_subscriber::registry()
        .with(layers)
        .with(filter)
        .init();
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn defaults_to_info_when_env_var_unset() {
        assert_eq!(resolve_log_level_from(None), "info");
    }

    #[test]
    fn reads_the_configured_level_from_the_env_var() {
        assert_eq!(resolve_log_level_from(Some("debug".to_string())), "debug");
    }
}
