// PostgreSQL 18.4 catalog MCP server — generated by mcpify. Do not hand-edit.

use serde_json::Value;

/// Substrings a JSON key is checked against (case-insensitively) before it's
/// logged. These are the secret shapes this PostgreSQL server actually uses.
const SENSITIVE_KEY_SUBSTRINGS: &[&str] = &["password", "secret", "authorization", "credential"];

pub fn is_sensitive_key(key: &str) -> bool {
    let lower = key.to_lowercase();
    SENSITIVE_KEY_SUBSTRINGS
        .iter()
        .any(|needle| lower.contains(needle))
}

fn redact_url_password(value: &str) -> String {
    let Some((scheme, rest)) = value.split_once("://") else {
        return value.to_string();
    };
    let authority_end = rest.find(['/', '?', '#']).unwrap_or(rest.len());
    let authority = &rest[..authority_end];
    let Some(at) = authority.rfind('@') else {
        return value.to_string();
    };
    let Some(colon) = authority[..at].find(':') else {
        return value.to_string();
    };
    format!(
        "{scheme}://{}:[REDACTED]{}",
        &authority[..colon],
        &rest[at..]
    )
}

/// Deep-clones `value`, replacing any object key matching a sensitive
/// pattern with `"[REDACTED]"`. Call this before logging any user- or
/// PostgreSQL-controlled JSON payload. Connection URL passwords are redacted
/// even though the key itself is simply named `url`.
pub fn sanitize(value: &Value) -> Value {
    match value {
        Value::Array(items) => Value::Array(items.iter().map(sanitize).collect()),
        Value::Object(map) => Value::Object(
            map.iter()
                .map(|(key, val)| {
                    let sanitized = if key.eq_ignore_ascii_case("url") {
                        val.as_str()
                            .map(redact_url_password)
                            .map(Value::String)
                            .unwrap_or_else(|| sanitize(val))
                    } else if is_sensitive_key(key) {
                        Value::String("[REDACTED]".to_string())
                    } else {
                        sanitize(val)
                    };
                    (key.clone(), sanitized)
                })
                .collect(),
        ),
        other => other.clone(),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    #[test]
    fn redacts_sensitive_keys_at_every_depth() {
        let input = json!({
            "username": "alice",
            "password": "hunter2",
            "nested": { "connectionPassword": "abc123", "note": "keep me" },
            "url": "postgresql://alice:db-secret@localhost/app",
        });

        let output = sanitize(&input);

        assert_eq!(output["username"], "alice");
        assert_eq!(output["password"], "[REDACTED]");
        assert_eq!(output["nested"]["connectionPassword"], "[REDACTED]");
        assert_eq!(output["nested"]["note"], "keep me");
        assert_eq!(output["url"], "postgresql://alice:[REDACTED]@localhost/app");
    }

    #[test]
    fn leaves_non_sensitive_values_untouched() {
        let input = json!({ "count": 3, "name": "widget" });
        assert_eq!(sanitize(&input), input);
    }
}
