// PostgreSQL 18.4 catalog MCP server — generated by mcpify. Do not hand-edit.

use crate::core::config_schema::{AuthMethod, Transport};
use crate::core::credential_storage::load_credential;

use super::request_credentials::RequestCredentials;

const CREDENTIAL_ACCOUNT: &str = "active-credentials";
const ENV_PREFIX: &str = "POSTGRES_MCP";

fn credentials_from_env() -> Option<RequestCredentials> {
    let username = std::env::var(format!("{ENV_PREFIX}_USERNAME")).ok()?;
    let password = std::env::var(format!("{ENV_PREFIX}_PASSWORD")).ok()?;
    if username.is_empty() {
        return None;
    }
    Some(RequestCredentials { username, password })
}

/// Resolves only credentials accepted by a native PostgreSQL password
/// connection. HTTP Basic is used solely to carry the same username/password
/// on an HTTP MCP request; it is not treated as a database auth mechanism.
pub struct AuthManager {
    cached_credentials: Option<RequestCredentials>,
}

impl AuthManager {
    pub fn new(auth_method: AuthMethod) -> Self {
        match auth_method {
            AuthMethod::Password => Self {
                cached_credentials: None,
            },
        }
    }

    #[cfg(test)]
    pub fn set_credentials(&mut self, credentials: RequestCredentials) {
        self.cached_credentials = Some(credentials);
    }

    async fn credentials(&mut self) -> anyhow::Result<RequestCredentials> {
        if let Some(credentials) = &self.cached_credentials {
            return Ok(credentials.clone());
        }

        if let Some(credentials) = credentials_from_env() {
            self.cached_credentials = Some(credentials.clone());
            return Ok(credentials);
        }

        if let Some(stored) = load_credential(CREDENTIAL_ACCOUNT)? {
            let credentials: RequestCredentials = serde_json::from_str(&stored)?;
            anyhow::ensure!(
                !credentials.username.is_empty(),
                "stored PostgreSQL username must not be empty"
            );
            self.cached_credentials = Some(credentials.clone());
            return Ok(credentials);
        }

        anyhow::bail!(
            "no PostgreSQL username/password is configured; set {ENV_PREFIX}_USERNAME and \
             {ENV_PREFIX}_PASSWORD or run `postgresql-mcp setup`"
        )
    }

    /// HTTP requests must supply their own PostgreSQL username/password and
    /// never inherit the server operator's local secrets. Stdio uses the
    /// environment/keychain credential cascade.
    pub async fn postgres_credentials(
        &mut self,
        transport: Transport,
        request_override: Option<&RequestCredentials>,
    ) -> anyhow::Result<RequestCredentials> {
        match (transport, request_override) {
            (Transport::Http, Some(credentials)) => Ok(credentials.clone()),
            (Transport::Http, None) => anyhow::bail!(
                "no PostgreSQL username/password was supplied on this HTTP request; local \
                 config/env/keychain is never used as a fallback over HTTP transport"
            ),
            (Transport::Stdio, _) => self.credentials().await,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn credentials(username: &str, password: &str) -> RequestCredentials {
        RequestCredentials {
            username: username.to_string(),
            password: password.to_string(),
        }
    }

    #[tokio::test]
    async fn seeded_postgresql_credentials_are_returned_for_stdio() {
        let mut manager = AuthManager::new(AuthMethod::Password);
        manager.set_credentials(credentials("alice", "secret"));

        assert_eq!(
            manager
                .postgres_credentials(Transport::Stdio, None)
                .await
                .unwrap(),
            credentials("alice", "secret")
        );
    }

    #[tokio::test]
    async fn http_uses_request_credentials_instead_of_local_credentials() {
        let mut manager = AuthManager::new(AuthMethod::Password);
        manager.set_credentials(credentials("local", "local-secret"));
        let request = credentials("request-user", "request-secret");

        assert_eq!(
            manager
                .postgres_credentials(Transport::Http, Some(&request))
                .await
                .unwrap(),
            request
        );
    }

    #[tokio::test]
    async fn http_without_request_credentials_never_falls_back() {
        let mut manager = AuthManager::new(AuthMethod::Password);
        manager.set_credentials(credentials("local", "local-secret"));

        assert!(
            manager
                .postgres_credentials(Transport::Http, None)
                .await
                .is_err()
        );
    }
}
