// PostgreSQL 18.4 catalog MCP server — generated by mcpify. Do not hand-edit.
//
// PostgreSQL username/password credentials resolved from env/keychain for
// stdio, or decoded from one incoming HTTP request's Basic Authorization
// header. They are used only for the native PostgreSQL connection and are
// never forwarded as an HTTP header.

use anyhow::Context;
use base64::Engine;
use base64::engine::general_purpose::STANDARD;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct RequestCredentials {
    pub username: String,
    pub password: String,
}

impl RequestCredentials {
    pub fn from_authorization_header(value: &str) -> anyhow::Result<Self> {
        let (scheme, encoded) = value
            .split_once(' ')
            .context("Authorization must use HTTP Basic credentials")?;
        anyhow::ensure!(
            scheme.eq_ignore_ascii_case("basic"),
            "Authorization must use HTTP Basic credentials"
        );
        let decoded = STANDARD
            .decode(encoded.trim())
            .context("Basic Authorization credentials are not valid base64")?;
        let decoded = String::from_utf8(decoded)
            .context("Basic Authorization credentials are not valid UTF-8")?;
        let (username, password) = decoded
            .split_once(':')
            .context("Basic Authorization credentials must contain username:password")?;
        anyhow::ensure!(
            !username.is_empty(),
            "PostgreSQL username must not be empty"
        );
        Ok(Self {
            username: username.to_string(),
            password: password.to_string(),
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn decodes_basic_credentials_without_losing_colons_in_the_password() {
        let creds =
            RequestCredentials::from_authorization_header("Basic YWxpY2U6czNjOnIzdA==").unwrap();
        assert_eq!(creds.username, "alice");
        assert_eq!(creds.password, "s3c:r3t");
    }

    #[test]
    fn rejects_non_basic_authorization() {
        assert!(RequestCredentials::from_authorization_header("Bearer token").is_err());
    }
}
