// PostgreSQL catalog MCP server — generated by mcpify. Do not hand-edit.

use crate::auth::request_credentials::RequestCredentials;
use crate::core::config_schema::Config;
use crate::data::store::EndpointRecord;
use crate::services::postgres_client::execute_operation;
use crate::validation::validator::{validate_input, validate_output};

/// Validates arguments against the input schema, executes the matching
/// catalog relation/function over PostgreSQL's native protocol with bound
/// values, and checks the response against the output schema — PRD §1.5's
/// `call` pipeline (architecture.md's 4-step `call` pipeline).
///
/// An output-schema mismatch is only logged, not raised: real-world OpenAPI
/// specs (e.g. Atlassian's published Jira Data Center spec) are frequently
/// wrong about response shape — declaring a single object where the API
/// actually returns an array, or an overly narrow `additionalProperties`
/// for a free-form bag of fields — and rejecting an otherwise-successful
/// call over a documentation bug would deny the caller real data it
/// already has in hand. Input validation still hard-fails: those arguments
/// are under the caller's control, not the upstream API's.
///
/// Takes an already-looked-up `EndpointRecord` rather than a `Connection`
/// and an `operation_id` to look up itself: `rusqlite::Connection` isn't
/// `Sync`, so a `&Connection` held across this function's `.await` points
/// (the PostgreSQL call) would make the caller's future non-`Send` — a hard
/// requirement for `#[tool]` methods (Story R6). Callers look the
/// endpoint up (a synchronous, `Connection`-scoped step) before calling
/// this function, not inside it.
pub async fn call_operation(
    endpoint: &EndpointRecord,
    config: &Config,
    credentials: &RequestCredentials,
    operation_id: &str,
    args: serde_json::Value,
) -> anyhow::Result<serde_json::Value> {
    validate_input(&config.api_version, operation_id, &args)?;

    let response = execute_operation(endpoint, config, credentials, &args).await?;

    if let Err(err) = validate_output(&config.api_version, operation_id, &response) {
        tracing::warn!(
            operation_id,
            error = %err,
            "response did not match the documented schema; returning it as-is"
        );
    }
    Ok(response)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// An operationId absent from the embedded validation schemas falls
    /// back to an always-valid schema (see `validator.rs`'s own tests for
    /// that behavior), so `validate_input` passes regardless of `args` --
    /// letting this reach `execute_operation`'s `connect` call, which fails
    /// fast and deterministically against a refused local port.
    #[tokio::test]
    async fn call_operation_reaches_execute_operation_after_passing_validation() {
        let _ = rustls::crypto::aws_lc_rs::default_provider().install_default();
        let endpoint = EndpointRecord {
            operation_id: "definitely-not-a-real-operation-id".to_string(),
            path: "/relations/pg_catalog/pg_class".to_string(),
            method: "GET".to_string(),
            summary: None,
            description: None,
            input_schema: serde_json::json!({}),
            output_schema: serde_json::json!({}),
        };
        let config: Config = serde_json::from_value(serde_json::json!({
            "url": "postgresql://127.0.0.1:1/testdb",
            "auth_method": "password"
        }))
        .unwrap();
        let credentials = RequestCredentials {
            username: "test".to_string(),
            password: "test".to_string(),
        };
        let error = call_operation(
            &endpoint,
            &config,
            &credentials,
            &endpoint.operation_id,
            serde_json::json!({}),
        )
        .await
        .unwrap_err();
        assert!(
            error
                .to_string()
                .contains("failed to connect to PostgreSQL")
        );
    }
}
