//! MCP prompts: guided PostgreSQL catalog-introspection and diagnostic
//! workflows. See `docs/mcp-prompts-workflow-plan.md` for the design this
//! module implements.
//!
//! Hand-authored (not generated by mcpify) -- kept separate from `tools/`.

pub mod router;

use rmcp::schemars;
use serde::Deserialize;

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct MasterWorkflowArgs {
    /// What the user is trying to accomplish, in their own words
    pub goal: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct SchemaIntrospectionWorkflowArgs {
    /// Schema to inspect (e.g. "public")
    pub schema_name: Option<String>,
    /// Table to inspect
    pub table_name: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct RolesPermissionsWorkflowArgs {
    /// Role/user to inspect or grant/revoke access for
    pub role_name: Option<String>,
    /// Schema the access question is scoped to
    pub schema_name: Option<String>,
    /// Table the access question is scoped to
    pub table_name: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct SessionLocksWorkflowArgs {
    /// Backend process id (pid) of the session in question
    pub pid: Option<String>,
    /// Database the session(s) of interest are connected to
    pub database_name: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct ReplicationWalWorkflowArgs {
    /// Name of the replication slot in question
    pub slot_name: Option<String>,
    /// Name of the logical replication publication in question
    pub publication_name: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct VacuumMaintenanceWorkflowArgs {
    /// Schema containing the table in question
    pub schema_name: Option<String>,
    /// Table to check vacuum/analyze health for
    pub table_name: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct QueryPerformanceWorkflowArgs {
    /// The slow query's text (or a distinguishing snippet of it)
    pub query_text: Option<String>,
    /// Table the query is centered on, if known
    pub table_name: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct ServerHealthConfigWorkflowArgs {
    /// Specific `pg_settings` name to look up, if known
    pub setting_name: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct ExtensionsFdwWorkflowArgs {
    /// Extension name in question
    pub extension_name: Option<String>,
    /// Foreign server name in question
    pub server_name: Option<String>,
}

#[derive(Debug, Deserialize, schemars::JsonSchema)]
pub struct DataProfilingWorkflowArgs {
    /// Table to explore/profile
    pub table_name: Option<String>,
}

/// Renders a short "what's already known" header to prepend to a prompt's
/// static markdown body, so its step-by-step instructions can tell the
/// calling LLM exactly which parameters still need to be asked for instead
/// of re-deriving that from the raw arguments every time.
pub fn render_context_header(fields: &[(&str, Option<&str>)]) -> String {
    let provided: Vec<String> = fields
        .iter()
        .filter_map(|(name, value)| value.map(|v| format!("- {name}: {v}")))
        .collect();
    let missing: Vec<String> = fields
        .iter()
        .filter(|(_, value)| value.is_none())
        .map(|(name, _)| format!("- {name}"))
        .collect();

    let mut out = String::from("## Context already provided\n");
    if provided.is_empty() {
        out.push_str("(none)\n");
    } else {
        out.push_str(&provided.join("\n"));
        out.push('\n');
    }
    if !missing.is_empty() {
        out.push_str(
            "\n## Still needed -- ask the user for these if the flow below requires them\n",
        );
        out.push_str(&missing.join("\n"));
        out.push('\n');
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn empty_field_list_renders_only_the_provided_header() {
        let header = render_context_header(&[]);
        assert_eq!(header, "## Context already provided\n(none)\n");
    }

    #[test]
    fn all_supplied_fields_are_listed_with_no_missing_section() {
        let header = render_context_header(&[("goal", Some("find slow queries"))]);
        assert!(header.contains("- goal: find slow queries"));
        assert!(!header.contains("Still needed"));
    }

    #[test]
    fn all_missing_fields_produce_no_provided_lines_but_list_every_field() {
        let header = render_context_header(&[("schema_name", None), ("table_name", None)]);
        assert!(header.contains("(none)"));
        assert!(header.contains("Still needed"));
        assert!(header.contains("- schema_name"));
        assert!(header.contains("- table_name"));
    }

    #[test]
    fn mixed_fields_split_correctly_between_provided_and_missing() {
        let header = render_context_header(&[
            ("schema_name", Some("public")),
            ("table_name", None),
            ("role_name", Some("app_readonly")),
            ("pid", None),
        ]);
        assert!(header.contains("- schema_name: public"));
        assert!(header.contains("- role_name: app_readonly"));
        assert!(header.contains("Still needed"));
        assert!(header.contains("- table_name"));
        assert!(header.contains("- pid"));
        assert!(!header.contains("- schema_name\n"));
    }
}
